# Generated by Django 6.0.7 on 2026-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_chatmessage_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
